fix a bug in polymorphic lambda forms
racket/typed-racket pull request #993
Opened 2020-11-09 02:59 UTC by capfredf

closes #940

2020-11-09 16:03 UTC, samth commented on typed-racket-lib/typed-racket/typecheck/tc-lambda-unit.rkt
> +        (syntax-property-remove a 'type-label) a))
```suggestion
        (syntax-property-remove a 'type-label)
        a))
```

2020-11-09 16:03 UTC, samth commented on typed-racket-lib/typed-racket/typecheck/tc-lambda-unit.rkt
> +(define (make-formals stx [not-in-poly #t])
This needs a comment explaining what's going on with `not-in-poly`

2020-11-09 16:03 UTC, samth commented on typed-racket-lib/typed-racket/base-env/prims.rkt
> +     (define (maybe-set-original-poly type-vars formals)
this function needs a comment explaining what it does

2020-11-11 15:30 UTC, capfredf commented
ping @samth

2020-11-11 17:57 UTC, samth requested changes

2020-11-11 17:57 UTC, samth commented on typed-racket-lib/typed-racket/private/syntax-properties.rkt
> +  ; marks syntax objects in formal parameters in polymorhpic lambdas forms.
```suggestion
  ; marks syntax objects in formal parameters in polymorphic lambdas forms.
```

2020-11-11 17:57 UTC, samth commented on typed-racket-lib/typed-racket/typecheck/tc-lambda-unit.rkt
> +;; checking non-polymorhic functions. In some scenarios, those functions are
spelling here too.

2020-11-11 17:57 UTC, samth commented on typed-racket-lib/typed-racket/typecheck/tc-lambda-unit.rkt
> +(define (make-formals stx [not-in-poly #t])
I think what's going on here is that we want to remove some information that might have out-of-scope type variables in particular cases. But the comment should explain why.

2020-11-12 04:00 UTC, capfredf commented
The third CI run failed due to the flaky random testing

2020-11-12 21:06 UTC, capfredf commented
ping @samth

2020-11-13 15:30 UTC, merged